# -*- coding: utf-8 -*-
#
# This file is part of Flask-SSO
# Copyright (C) 2014, 2015, 2016 CERN.
#
# Flask-SSO is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

# Travis CI file, that integrates with coveralls for reporting test coverage.

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: jirikuncar
  password:
    secure: txNr7JfTM8P69jTi8OJygQdUtKsw6f6BaBzG7OrqQ739x1wLlR6TO4282rHga/Cq4SMyGD9FHebhS1craYV1WmmsgebXpU1sP6RNYMXsBvQjloNTRbf8AnzEsB2GwC5fIHUgvKBVkXNAxm47atfu2QDlWnykvIqOeOi+IZLDk2Q=
  on:
    python: "2.7"
    repo: inveniosoftware/flask-sso
    tags: true
